let data = [{
        name: "Node JS Tutorial",
        instructor: "NetNinja",
        url: "https://www.youtube.com/playlist?list=PL4cUxeGkcC9gcy9lrvMJ75z9maRw4byYp",
        description: "A step by step walk-through what Node JS is, and how it all works. We'll also be creating a Node JS application from scratch using express, and hook it up to MongoDB - a noSQL database perfect for using with Node.",
        image: "",
        tags: ["nodejs", "javascript", "web"],
    },
    {
        name: "Intro To React",
        instructor: "Ishan Sharma",
        url: "https://blog.ishandeveloper.com/react-intro",
        description: "A comprehensive beginner friendly guide to what react is and how you can benefit from it.",
        image: "intro-react.png",
        tags: ["react", "javascript", "web"],
    },
    {
        name: "Flutter Complete Course",
        instructor: "Pawan Kumar",
        url: "https://www.youtube.com/watch?v=Ib2FlirtcmE",
        description: "Get Started with Flutter and learn how to build natively compiled applications for mobile (Android & iOS), web, and desktop from a single codebase.",
        image: "",
        tags: ["flutter", "app"],
    },
    {
        name: "Intro To Linux",
        instructor: "Ishan Sharma",
        url: "https://blog.ishandeveloper.com/linux-intro",
        description: "One of the most important tools for a programmer is the Operating System, it runs your whole device and it’s important to choose the one that suits you the best!",
        image: "intro-linux.png",
        tags: ["linux", "bash"],
    },
    {
        name: "Neural Networks and Deep Learning",
        instructor: "Andrew Ng",
        url: "https://www.coursera.org/learn/neural-networks-deep-learning",
        description: "If you want to break into cutting-edge AI, this course will help you do so. Deep learning engineers are highly sought after, and mastering deep learning will give you numerous new career opportunities. Deep learning is also a new 'superpower' that will let you build AI systems that just weren't possible a few years ago.",
        image: "",
        tags: ["machine learning", "ai", "deep learning", "neural networks"],
    },
    {
        name: "React Native Tutorial for Beginners",
        instructor: "The Net Ninja",
        url: "https://www.youtube.com/watch?v=ur6I5m2nTvk&list=PL4cUxeGkcC9ixPU-QkScoRBVxtPPzVjrQ",
        description: "Hey gang, and welcome to your first React Native tutorial for beginners. In this series we'll go from novice to ninja and create a React Native app from scratch. irst though, we'll get set up and talk about what React Native actually is. ",
        image: "",
        tags: ["react-native", "javascript"],
    },
    {
        name: "Fullstack React GraphQL TypeScript Tutorial",
        instructor: "Ben Awad",
        url: "https://www.youtube.com/watch?v=I6ypD7qv3Z8",
        description: "A fullstack project course from scratch using React, Next.js, TypeScript, GraphQL, NodeJs, ORM, PostgreSQL.",
        image: "",
        tags: ["react", "nextjs", "nodejs", "graphql", "typescript", "javascript"],
    },
    {
        name: "Angular Crash Course for Beginners",
        instructor: "Hitesh Choudhary",
        url: "https://www.youtube.com/watch?v=T_Fe4IaG0KU",
        description: "In the first part of the video, we will talk about details of Angular and some common questions about it.In the second part of Angular crash course video, we will create a basic project to get hands-on with Angular.",
        image: "",
        tags: ["Angular", "typescript", "javascript"],
    },
];